name: groove2groove
channels:
  - defaults
  - conda-forge/label/cf201901
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py36_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.0=cuda9.0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libsndfile
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1d=h7b6447c_3
  - pip=19.3.1=py36_0
  - python=3.6.8=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=42.0.2=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - astroid==2.3.3
    - attrs==19.3.0
    - audioread==2.1.8
    - backcall==0.1.0
    - backports.tempfile==1.0
    - backports.weakref==1.0.post1
    - bokeh==1.4.0
    - cached-property==1.5.1
    - cffi==1.13.2
    - coloredlogs==10.0
    - confugue==0.1.1
    - cycler==0.10.0
    - decorator==4.4.1
    - gast==0.3.2
    - grpcio==1.26.0
    - h5py==2.10.0
    - humanfriendly==4.18
    - imageio==2.9.0
    - importlib-metadata==1.3.0
    - intervaltree==3.0.2
    - ipykernel==5.1.3
    - ipython==7.11.0
    - ipython-genutils==0.2.0
    - isort==4.3.21
    - jedi==0.15.2
    - jinja2==2.10.3
    - joblib==0.14.1
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.2.0
    - lazy-object-proxy==1.4.3
    - librosa==0.7.1
    - llvmlite==0.31.0
    - lmdb==0.98
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mccabe==0.6.1
    - mido==1.2.6
    - more-itertools==8.0.2
    - museflow==1.0.0
    - networkx==2.5
    - note-seq==0.0.1
    - numba==0.48.0
    - numpy==1.18.0
    - packaging==19.2
    - pandas==0.25.3
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.2.1
    - pluggy==0.13.1
    - pretty-midi==0.2.8
    - prompt-toolkit==3.0.2
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - py==1.8.1
    - pycparser==2.19
    - pydocstyle==5.0.1
    - pygments==2.5.2
    - pylint==2.4.4
    - pylint-quotes==0.2.1
    - pyparsing==2.4.6
    - pytest==5.3.2
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyyaml==5.2
    - pyzmq==18.1.1
    - resampy==0.2.2
    - scikit-image==0.17.2
    - scikit-learn==0.22
    - scipy==1.2.0
    - six==1.13.0
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - soundfile==0.10.3.post1
    - tensorboard==1.12.2
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - tornado==6.0.3
    - tqdm==4.41.1
    - traitlets==4.3.3
    - typed-ast==1.4.0
    - wcwidth==0.1.7
    - werkzeug==0.16.0
    - wrapt==1.11.2
    - zipp==0.6.0